// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvwOC53GWOtb5i2G39hKR5soLTMdvj8KU',
    appId: '1:558914129354:web:f479d2b9491e1c9aafd333',
    messagingSenderId: '558914129354',
    projectId: 'stock-eb628',
    authDomain: 'stock-eb628.firebaseapp.com',
    databaseURL: 'https://stock-eb628-default-rtdb.firebaseio.com',
    storageBucket: 'stock-eb628.appspot.com',
    measurementId: 'G-LPNKXMV2N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzaD11YDAR0nETy4sVRouJvHoFsHqfVC0',
    appId: '1:558914129354:android:7affcaf30157bb23afd333',
    messagingSenderId: '558914129354',
    projectId: 'stock-eb628',
    databaseURL: 'https://stock-eb628-default-rtdb.firebaseio.com',
    storageBucket: 'stock-eb628.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrgrkWARnNhWgqkVmU_mi9_RC6Qx_4DDU',
    appId: '1:558914129354:ios:209cd29fbcd191dfafd333',
    messagingSenderId: '558914129354',
    projectId: 'stock-eb628',
    databaseURL: 'https://stock-eb628-default-rtdb.firebaseio.com',
    storageBucket: 'stock-eb628.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrgrkWARnNhWgqkVmU_mi9_RC6Qx_4DDU',
    appId: '1:558914129354:ios:2e0786d7e7269ef3afd333',
    messagingSenderId: '558914129354',
    projectId: 'stock-eb628',
    databaseURL: 'https://stock-eb628-default-rtdb.firebaseio.com',
    storageBucket: 'stock-eb628.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
